### ISSUE TITLE
Why game no done yet??

### ISSUE THREAD

**Issue by Iulian-Tudor** [GhitescuCaterina/snake-game-python#1]
I WANNA PLAY!

**Comment by Iulian-Tudor** [comment]
![3qdwjn](https://github.com/GhitescuCaterina/snake-game-python/assets/100115312/21559f6e-0c90-40cd-808f-aa6579384ec3)

**Comment by JoxtaQrst** [comment]
![imagine_2023-12-04_201643688](https://github.com/GhitescuCaterina/snake-game-python/assets/44101553/07933658-d9f2-4216-b830-29a4b8e5e75c)
